# Generated by Django 3.2.25 on 2024-06-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfproject', '0009_remove_splitpdf_original_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitpdf',
            name='split_pdf_name',
            field=models.CharField(max_length=255),
        ),
    ]
