# Generated by Django 3.2.25 on 2024-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfproject', '0010_alter_splitpdf_split_pdf_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splitpdf',
            old_name='split_date',
            new_name='split_date_time',
        ),
        migrations.AddField(
            model_name='splitpdf',
            name='split_pdf_location',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
