# Generated by Django 3.2.25 on 2024-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfproject', '0011_auto_20240629_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitpdf',
            name='split_pdf_name',
        ),
        migrations.AddField(
            model_name='splitpdf',
            name='original_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projectoutput/'),
        ),
    ]
